// Code generated by SQLBoiler 4.5.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Albums           string
	Artists          string
	RecentListenData string
	RecentListens    string
	Songs            string
	Thumbnails       string
	TopArtistData    string
	TopArtists       string
	TopSongData      string
	TopSongs         string
	Users            string
}{
	Albums:           "albums",
	Artists:          "artists",
	RecentListenData: "recent_listen_data",
	RecentListens:    "recent_listens",
	Songs:            "songs",
	Thumbnails:       "thumbnails",
	TopArtistData:    "top_artist_data",
	TopArtists:       "top_artists",
	TopSongData:      "top_song_data",
	TopSongs:         "top_songs",
	Users:            "users",
}
