// Code generated by SQLBoiler 4.5.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("Albums", testAlbumsUpsert)

	t.Run("Artists", testArtistsUpsert)

	t.Run("RecentListenData", testRecentListenDataUpsert)

	t.Run("RecentListens", testRecentListensUpsert)

	t.Run("Songs", testSongsUpsert)

	t.Run("Thumbnails", testThumbnailsUpsert)

	t.Run("TopArtistData", testTopArtistDataUpsert)

	t.Run("TopArtists", testTopArtistsUpsert)

	t.Run("TopSongData", testTopSongDataUpsert)

	t.Run("TopSongs", testTopSongsUpsert)

	t.Run("Users", testUsersUpsert)
}
